FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir -e .

COPY dashboard ./dashboard
COPY .streamlit ./.streamlit
COPY data/processed/policylens.duckdb ./data/processed/policylens.duckdb
COPY reports ./reports

EXPOSE 8080
CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8080", "--server.address=0.0.0.0"]
