import json
import re

from civiclens.config import ROOT_DIR
from civiclens.lineage.emit import LINEAGE_LOG_PATH

README_PATH = ROOT_DIR / "policylens_README.md"
SECTION_START = "<!-- LINEAGE_GRAPH_START -->"
SECTION_END = "<!-- LINEAGE_GRAPH_END -->"

_RAW_ZIP_RE = re.compile(r"^data/raw/\d+- Dataful\.zip$")


def _collapse_raw_inputs(names: list[str]) -> list[str]:
    """Collapse the 17 per-commodity raw zips into one node so the diagram stays readable."""
    raw_zips = [n for n in names if _RAW_ZIP_RE.match(n)]
    others = [n for n in names if n not in raw_zips]
    if raw_zips:
        others.append(f"data/raw/*.zip ({len(raw_zips)} commodity files)")
    return others


def load_jobs() -> dict[str, dict[str, list[str]]]:
    """Read the accumulated OpenLineage JSONL and return the latest COMPLETE inputs/outputs
    per job name.
    """
    jobs: dict[str, dict[str, list[str]]] = {}
    for line in LINEAGE_LOG_PATH.read_text().splitlines():
        if not line.strip():
            continue
        event = json.loads(line)
        if event["eventType"] != "COMPLETE":
            continue
        job_name = event["job"]["name"]
        jobs[job_name] = {
            "inputs": _collapse_raw_inputs([d["name"] for d in event.get("inputs", [])]),
            "outputs": [d["name"] for d in event.get("outputs", [])],
        }
    return jobs


def build_mermaid(jobs: dict[str, dict[str, list[str]]]) -> str:
    lines = ["```mermaid", "flowchart LR"]
    node_ids: dict[str, str] = {}

    def node_id(name: str) -> str:
        if name not in node_ids:
            node_ids[name] = f"n{len(node_ids)}"
            lines.append(f'    {node_ids[name]}["{name.replace(chr(34), chr(39))}"]')
        return node_ids[name]

    for job_name, io in jobs.items():
        for inp in io["inputs"]:
            in_id = node_id(inp)
            for out in io["outputs"]:
                out_id = node_id(out)
                lines.append(f"    {in_id} -->|{job_name}| {out_id}")

    lines.append("```")
    return "\n".join(lines)


def update_readme(mermaid_block: str) -> None:
    text = README_PATH.read_text(encoding="utf-8")
    section = (
        f"{SECTION_START}\n"
        "## Data Lineage\n\n"
        "_Auto-generated by `make lineage` from real OpenLineage events emitted during "
        "`make ingest` / `make clean` / warehouse build "
        "(`data/interim/lineage_events.jsonl`) -- not hand-drawn._\n\n"
        f"{mermaid_block}\n"
        f"{SECTION_END}"
    )
    if SECTION_START in text and SECTION_END in text:
        pattern = re.compile(
            re.escape(SECTION_START) + r".*?" + re.escape(SECTION_END), re.DOTALL
        )
        text = pattern.sub(section, text)
    else:
        marker = "\n---\n"
        idx = text.find(marker)
        insertion = f"\n{section}\n"
        text = text[:idx] + insertion + text[idx:] if idx != -1 else text + insertion
    README_PATH.write_text(text, encoding="utf-8")


def main() -> None:
    jobs = load_jobs()
    if not jobs:
        raise SystemExit(
            "No lineage events found -- run `make ingest`, `make clean`, and the "
            "warehouse build first."
        )
    mermaid = build_mermaid(jobs)
    update_readme(mermaid)
    print(f"Lineage graph regenerated in {README_PATH} from {len(jobs)} jobs.")


if __name__ == "__main__":
    main()
